spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"


accounts:
  message: "Welcome to bank accounts related QA APIs"
  contactDetails:
    name: "Carlos buendia -QA"
    email: "carlosQA@buendia.com"
  onCallSupport:
    - 674571962
    - 692245802